template:
    name: 
        {
            pt: 'Divulgação de Erros da Aplicação',
            en: 'Application Error Disclosure'
        }
    type: Web
    category: Misconfiguration
    subcategory: 'Visible Detailed Error/Debug Page'
    description: 
        { 
            pt: "Vazamento de erros é uma vulnerabilidade em que uma aplicação revela dados sensíveis, tais como detalhes técnicos da aplicação web, ambiente, ou dados específicos do usuário.\r\nDados confidenciais podem ser usados por um atacante para explorar a aplicação Web alvo, sua rede de hospedagem ou seus usuários. Em sua forma mais comum, o vazamento de erros é o resultado de manipulação incorreta de erros da aplicação, que\r\npodem revelar informações sensíveis como a localização do arquivo que gerou a exceção.", 
            en: 'Bug leakage is a vulnerability where an application reveals sensitive data, such as technical details of the web application, environment, or user-specific data. Sensitive data can be used by an attacker to exploit the target web application, its hosting network or its users. In its most common form, error leakage is the result of incorrect application error handling, which can reveal sensitive information such as the location of the file that generated the exception.' 
        }
    recomendation: 
        { 
            pt: 'Use mensagens de erro genéricas personalizadas para evitar o vazamento de informações confidenciais em formação. Certifique-se de que cada entrada do usuário seja devidamente validada em todos os campos de entrada do aplicativo.', 
            en: 'Use custom generic error messages to avoid leaking confidential information in formation. Make sure that each user input is properly validated in all input fields in the application.' 
        }
    references: ['https://www.owasp.org/index.php/Improper_Error_Handling']
