template:
    name: 
        {
            pt: 'Configurações incorretas no CORS - Origin',
            en: 'Cors Origin Misconfiguration'
        }
    type: Web
    category: Misconfiguration
    subcategory: 'Origin-Resource-Sharing (CORS)'
    description: 
        { 
            pt: 'Alterando o parâmetro “Origin”, podemos ver que o CORS está aceitando como endereço válido, desta forma podemos falsificar as requisições com outros endereços. ', 
            en: 'By changing the “Origin” parameter, we can see that CORS is accepting it as a valid address, in this way we can falsify the requests with other addresses.' 
        }
    recomendation: 
        { 
            pt: 'Não confie apenas no cabeçalho Origin para verificações de controle de acesso. O navegador sempre envia esse cabeçalho em solicitações CORS, mas pode ser falsificado fora do navegador.', 
            en: 'Don''t just rely on the Origin header for access control checks. The browser always sends this header in CORS requests, but it can be spoofed outside the browser.' 
        }
    references: ['https://cheatsheetseries.owasp.org/cheatsheets/HTML5_Security_Cheat_Sheet.html']
